services:
  client:
    build: ./client
    container_name: client
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - task-service
      - user-service

  task-service:
    build: ./task-service
    container_name: task-service
    restart: always
    env_file:
      - ./task-service/.env
    ports:
      - "5000:5000"
    depends_on:
      - user-service

  user-service:
    build: ./user-service
    container_name: user-service
    restart: always
    env_file:
      - ./user-service/.env
    ports:
      - "4000:4000"

  notification-service:
    build: ./notification-service
    container_name: notification-service
    restart: always
    env_file:
      - ./notification-service/.env
    ports:
      - "5001:5001"
    depends_on:
      - task-service