apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  MONGO_URI: bW9uZ29kYitzcnY6Ly95b3VjZWZraGVsYWlmaWFfZGJfdXNlcjoxWjIySmJQNnNQSUV6c3lqQGNsdXN0ZXIwLm5yanBiaGYubW9uZ29kYi5uZXQvZGV2b3BzP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ==
  EMAIL_USER: bWluaXByb2plY3RjbG91ZDFAZ21haWwuY29t
  EMAIL_PASS: c2J1dGhheWJndG14eGd2bw==
  JWT_SECRET: MTIz
